name: Deploy Seguro no Cofre Digital

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Simulando Deploy Seguro
        run: |
          echo "Iniciando o deploy seguindo a missão da image_e021e1.png..."
          echo "Verificando segredos..."
          # O comando abaixo mostrará apenas *** nos logs devido ao Log Masking automático
          echo "A chave secreta recuperada do cofre é: ${{ secrets.CHAVE_MESTRA_DO_COFRE }}"
          echo "Configuração concluída com sucesso!"
